export const ADD_EXERCISE_TO_LIST_OF_EXERCISES = 'ADD_EXERCISE';
export const DELETE_EXERCISE_FROM_LIST_OF_EXERCISES = 'DELETE_EXERCISE';
export const EDIT_EXERCISE_FROM_LIST_OF_EXERCISES = 'DELETE_EXERCISE';
export const CREATE_WORKOUT = 'CREATE_WORKOUT';
export const CHANGE_WEIGHT = 'CHANGE_WEIGHT';
export const CHANGE_REPS = 'CHANGE_REPS';
export const CHANGE_DISTANCE = 'CHANGE_DISTANCE';
export const CHANGE_TIME = 'CHANGE_TIME';
